### ISSUE TITLE
Pin Docker Image Versions in GitHub Actions

### ISSUE THREAD

**Issue by 5000164** [Codium-ai/pr-agent#1034]
## Summary

To enhance the reliability and consistency of CI/CD pipeline, I propose using Docker image digests instead of tags in GitHub Actions.

## Details

Currently, the action is using Docker image tags, which can lead to unexpected changes or breaking updates when the tagged image is updated.
By specifying the image digest, we ensure that the exact same image is used every time, providing a more stable and reproducible environment.

Reference: https://github.com/Codium-ai/pr-agent/blob/6135bf1f53f78ba265b5958ac1475f49463fce81/Dockerfile.github_action_dockerhub#L1

**Comment by 5000164** [comment]
Hi, thank you for your response.

My concern is about using tags like `github_action` in the GitHub Actions. Tags can point to different images over time, which might cause unexpected changes or instability in the CI/CD pipeline. By using the `github_action` tag, the workflow always pulls the latest image associated with that tag at the time of execution.

To address this, I propose using Docker image digests instead of tags. Digests uniquely identify an image based on its content, ensuring we use the exact same image every time. This enhances the reliability and security of our pipeline.

For example, instead of:

```Dockerfile
FROM codiumai/pr-agent:github_action
```

We would use:

```Dockerfile
FROM codiumai/pr-agent@sha256:<digest>
```

This way, we ensure a stable and reproducible environment.

**Comment by mrT23** [comment]
If you want to work with a stable version (v0.22, v0.23, ..), use the relevant one in your yaml file:

https://pr-agent-docs.codium.ai/installation/github/#run-as-a-github-action
![image](https://github.com/user-attachments/assets/93aee6c1-d526-4cb7-a946-a7216ad851aa)

These versions are **fixed**. we release a new version once a month.

In any case, we don't intend to change our dockerhub release mechanism

**Comment by mrT23** [comment]
it is included

**Comment by no-yan** [comment]
> If you want to work with a stable version (v0.22, v0.23, ..), use the relevant one in your yaml file:

@mrT23 You cannot use the PR Agent stable version by that.
For all versions, the Dockerfile's tag [`codiumai/pr-agent:github_action`](https://github.com/Codium-ai/pr-agent/blob/dc917587ef63304927b858c8cf1c57157ff1ff19/Dockerfile.github_action_dockerhub#L1) points to the same tag(i.e. `github_action`). Therefore, the same container is built regardless of the version specified in Actions.
![image](https://github.com/user-attachments/assets/40c01eed-4702-4421-9fe2-5d9f39d3fce2)
![image](https://github.com/user-attachments/assets/c559175a-269d-44be-98ef-1f8ec1a4d9c6)
![image](https://github.com/user-attachments/assets/a6f95126-8cc9-44c2-a22f-4b1dd3a4eb92)
[Verification repository link](https://github.com/no-yan/pr-agent-sandbox/pulls)

As a result, if you specify any version in GitHub Actions, it will be ignored. Users using v0.12 might not expect that the codiumai/pr-agent:github_action running is actually the one updated just two days ago.

This problem has already been noted. 　See https://github.com/Codium-ai/pr-agent/issues/1015#issuecomment-2213707836


To solve this, consider the following options:

1. For each release, update the Dockerfile to use a unique tag for that version (e.g., codiumai/pr-agent:v0.23 or codiumai/pr-agent:0.23-github_action).
2. Stop using Docker Hub and instead build the Dockerfile.github_action directly in GitHub Actions. 

Second approach ensures the correct version is used, because GitHub Actions will check out the exact source code for the specified tag (like v0.23).

**Comment by no-yan** [comment]
It's a significant issue that versioning is clearly not working correctly with GitHub Actions.
It would be wise to separate discussions about running appropriately version-managed containers from those about pinning images for security hardening.

**Comment by mrT23** [comment]
ok, we will look into that issue

**Comment by mrT23** [comment]
@5000164 @no-yan 

try referring to the docker directly instead:

```
    steps:
      - name: PR Agent action step
        id: pragent
        uses: docker://codiumai/pr-agent:0.23-github_action
```

it worked for me, with the correct sha.

If it works also for you, you can, and should, open a PR to update the documentation with the new methodology

**Comment by 5000164** [comment]
`uses: docker://codiumai/pr-agent@sha256:14165e525678ace7d9b51cda8652c2d74abb4e1d76b57c4a6ccaeba84663cc64` worked for me, I will create a PR to document it.

**Comment by 5000164** [comment]
opend #1042

**Comment by 5000164** [comment]
I've found a way to fix the image digest, and the PR has been merged, so I'll be closing this issue.
Thank you for your assistance.
