### ISSUE TITLE
Use `instructor` for Parsing and Validation

### ISSUE THREAD

**Issue by h0rv** [Codium-ai/pr-agent#1044]
When testing watsonx.ai models to add support, my team and I were having trouble with extraction and the model not following the correct yaml format. The retry and validation logic is simple in this project, and I think it would beneficial to use the popular package `instructor` (https://github.com/jxnl/instructor/) to abstract this logic away as they have a lot of good techniques (prompting, retrying from parsing errors, etc.) that is not implemented here.

**Comment by mrT23** [comment]
watsonx.ai models are not good enough to handle code, definitely not PR code, which is highly complicated (patches, with limited scope)

PR Agent requires models like GPT or Claude to provide reasonable results. Use them instead.

In any case, Instructor wouldn't improve the results. It will just do endless retries, since watsonx.ai models fail to obey the prompt instructions and generate a valid YAML.

**Comment by h0rv** [comment]
That is not true, the retries send back the parsing errors, which the models do a fine job of doing. The current code just does an entire retry which will retry the entire thing again, which will, yes, endlessly retry.

**Comment by h0rv** [comment]
Also, to use this in an enterprise setting, it is not possible for many companies to be able to use the state of the art from OpenAI and Anthropic, especially when they have their own LLM offering.

**Comment by mrT23** [comment]
Consistently doing multiple calls because of an incapable model is a bad methodology.
Hence, PR-Agent is not gonna incorporate Instructer, or any other package with that logic.

I understand that some companies don't allow models like OpenAI, or communicating data outside.
For that, we at CodiumAI **fine-tune** open-source models (including IBM granite) to actually provide good performance on PR code tasks, and still maintain security limitations by on-prem deployment.  This is part of PR-Agent pro offering for enterprises. If relevant, you are welcome to contact us.
If not, try contacting the granite team, and ask them to deploy better models for structure output. Its a basic ability for LLMs.

All the best

**Comment by h0rv** [comment]
I understand, but I do think adding this library (or at least better parsing and structured output in general) will improve the application. Some people are unable to use OpenAI or Anthropic. Also, some users may be okay with losing some performance and are okay with running smaller, local models. Fine-tuning is a possible solution to this, but a much faster and cheaper solution is improved prompting, better retries (sending parse error back to model to fix), etc.
