### ISSUE TITLE
SubSequent Commits on PR

### ISSUE THREAD

**Issue by r-ashraf** [Codium-ai/pr-agent#1182]
We are using pr agent to do AI reviews on PRs hosted on BitBucket.On very first commit, PR is created and we auto run the review. Ideally suppose, AI reviewer adds 10 suggestions. the PR author determines 3 are not applicable. Now author make more changes, does new commit and updates the PR, at this point, the second run of AI PR review, shouldnt re add the same suggestions as the one from the initial commit and run. Is this possible

**Comment by mrT23** [comment]
PR-Agent pro has many capabilities for implementing the proposed suggestions, and presenting them in a nice a concise way, including repeated suggestions.
https://pr-agent-docs.codium.ai/overview/pr_agent_pro/

 
Unfurtunatly, since bitbucket is so outdated, it does not provide even the minimal graphic capabilities needed for these abilities. And we need to present all the suggestions instead as code comments.

If you pay money for bitbucket, I recommend you to contact them and demand improvement. they are way behind github and gitlab
