### ISSUE TITLE
Gitlab Webhook Documentation

### ISSUE THREAD

**Issue by faberto** [Codium-ai/pr-agent#1300]
I have tried to follow the 
https://qodo-merge-docs.qodo.ai/installation/gitlab/#run-a-gitlab-webhook-server

While doing the configurations it is very unclear:

> In the [gitlab] section, fill in personal_access_token and shared_secret. 

There is no `shared_secret` option

> Set deployment_type to 'gitlab' in [configuration.toml](https://github.com/Codium-ai/pr-agent/blob/main/pr_agent/settings/configuration.toml)

There is no `deployment_type ` option.

Has this been mixed up with gitlab?

**Comment by mrT23** [comment]
Closing due to inappropriate language.

You are a free user, in an open source, who has not contributed a single line of code yet to the code base.

If you failed to understand the instructions (which many before you were able to understand), you should ask for help in a respectful and appropriate manner.
