### ISSUE TITLE
[Feature Request] - Ability to customize the prompts

### ISSUE THREAD

**Issue by georgeseifada** [Codium-ai/pr-agent#154]
It would be great to have the ability to customize the prompts, or at least add lines to the initial description for extra guidance. For example, for the [code suggestion prompt](https://github.com/Codium-ai/pr-agent/blob/main/pr_agent/settings/pr_code_suggestions_prompts.toml), users might want to add an extra line for telling the LLM to explicitly suggest type hints, possible unit tests, etc.

**Comment by KalleV** [comment]
+1 The automatic reviews are already great but they would potentially be even better by adding a high-level description of the project the code change is being applied to along with other customizations like you mentioned.

**Comment by mrT23** [comment]
Hi @georgeseifada, thanks for the feedback

Because we use a dedicated JSON format, our tools are customizable and adjustable. 
In the `configuration` files you can control each tool. For example, pr-reviewer (/review):
![image](https://github.com/Codium-ai/pr-agent/assets/21198860/25d93c33-624a-4237-8b45-d6945ef87623)
This configuration enables you to turn on/off different fields.
The 'score' field, for example, was added in the PR: https://github.com/Codium-ai/pr-agent/pull/89, and you can see it was quite easy and straightforward to add.  Other fields can also be added easily

In addition,  regarding your suggestion for adding possible "extra instructions" for code suggestion - good idea :-)
So a possible format will be:
/imporve -extra_instruction="focus on the file ..."

**Comment by mrT23** [comment]
been addressed in 
https://github.com/Codium-ai/pr-agent/pull/159
