### ISSUE TITLE
Failure in `/improve` command

### ISSUE THREAD

**Issue by zmeir** [Codium-ai/pr-agent#221]
I encountered the following error when calling `/improve` in a large PR when requesting many code suggestions. Here's an example PR I tested this on: https://github.com/zmeir/pr-agent/pull/4

I ran the command from CLI:
```bash
python3 pr_agent/cli.py --pr_url https://github.com/zmeir/pr-agent/pull/4 improve --config.verbosity_level=3 --pr_code_suggestions.num_code_suggestions=50
```

And this is the error:
```log
ERROR:root:Failed to publish code suggestion, error: 422 {"message": "Unprocessable Entity", "errors": ["Pull request review thread line must be part of the diff, Pull request review thread start line must be part of the same hunk as the line., and Pull request review thread diff hunk can't be blank"], "documentation_url": "https://docs.github.com/rest/pulls/reviews#create-a-review-for-a-pull-request"}
```

Full log attached:  
[error.log](https://github.com/Codium-ai/pr-agent/files/12387628/error.log)

**Comment by mrT23** [comment]
i will take a look
but one way or another, you can't get even close to 50 suggestions in a single call - there is not enough tokens

in any case, i am thinking about implementing a different tool for large PRs, that will divide the code changes to several chunks, and run a suggestion call per chunk, and aggregate the results. this will enable getting more suggestions, and be more responsive to the PR size. The downside is off-course multiple calls, so should be taken into consideration

**Comment by zmeir** [comment]
Thanks @mrT23 !

About the high number of suggestions - I know it's too much, I only set this configuration in the test to expose the issue. I usually ask for 5 suggestions but then it's flakier and I see this issue only once in a while. So that changing of the configuration is just to help reproduce and existing issue that still occurs but in lower frequency with the default configuration.

**Comment by mrT23** [comment]
Ok, i think i understand the problem

when you ask for 50(!) suggestions, the model tries to "think" of so many. But to do that, he usually invents some bad\invalid ones.

then he tries to generate 50, but stops due to lack of tokens after 3-5
among them, sometimes one or more suggestion is invalid (bad line number)

when we try to output the suggestions as a group, we fail
`self.git_provider.publish_code_suggestions(code_suggestions)`

so i added a fallback that we try to send each suggestion seperatly in that case:
```
        is_successful = self.git_provider.publish_code_suggestions(code_suggestions)
        if not is_successful:
            logging.info("Failed to publish code suggestions, trying to publish each suggestion separately")
            for code_suggestion in code_suggestions:
                self.git_provider.publish_code_suggestions([code_suggestion])
```


i tested this with and without the 'extended' mode from here:
https://github.com/Codium-ai/pr-agent/pull/229
and it works

i also hope that the improved prompt will reduce the number of invalid suggestions
