### ISSUE TITLE
[Add Docs Tool] File type detection for code documentation

### ISSUE THREAD

**Issue by KalleV** [Codium-ai/pr-agent#379]
I tried out https://github.com/Codium-ai/pr-agent/blob/d13a92515b3810d4a0fd02a060eafc26441f15d8/docs/ADD_DOCUMENTATION.md, and it works great! I did run into an issue with it applying JSDoc / JS comment syntax to SQL migration files, though.

Multi-language support would be great to add to this tool!

**Comment by mrT23** [comment]
@KalleV  can you share more info on what went wrong ? maybe reproduction example ?

this feature is supposed to be multi-language

@hussam789

**Comment by KalleV** [comment]
Sure, here's a reproduction on a SQL file: https://github.com/KalleV/pr-agent-tester/pull/3

**Comment by mrT23** [comment]
@KalleV  thanks, @hussam789  (the feature owner 😄  ) will take a look.

Regardless,  we are going to add a similar ability to the IDE extension - adding docstring to new or edited components before a PR

I think it will be even more useful there, because the most convenient place to edit\enhance your code is the IDE, not comittable suggestions in Github, which are harder to inspect and debug. So stay tuned.

**Comment by hussam789** [comment]
@KalleV @mrT23 
I opened a PR fixing the issue for SQL and other potential script extensions.
https://github.com/Codium-ai/pr-agent/pull/385

Let me know if I missed an extension you want to blacklist for this feature.

**Comment by hussam789** [comment]
@KalleV 

This feature is meant to document code components (methods, classes...etc), not scripts (SQL, Bash...etc).

I opened a PR that has a blacklist of extensions so `add_doc` feature is restricted only to programming languages.
