### ISSUE TITLE
fea: add the information about the target branch in the agent

### ISSUE THREAD

**Issue by TomDarmon** [Codium-ai/pr-agent#631]
Currently, it doesn't look like pr_agent knows what is the target branch of the PR. 

Currently I want to create a custom label that will tag my PR if the target branch is main. But when asking questions about the PR the agent does not seem to know what the target branch is, so I doubt it will work.

<img width="718" alt="image" src="https://github.com/Codium-ai/pr-agent/assets/36815861/9cf9223d-514f-4ad7-b42f-8532b835636e">

Am I missing something ?

**Comment by mrT23** [comment]
Correct, we dont give the 'target branch' as input to the model.

**Comment by TomDarmon** [comment]
Is it an improvement that we could expect is the future ? I don't want to insist, I just want to know if I should find another way to achieve my goal or if just waiting a few weeks would be enough!

**Comment by mrT23** [comment]
Every time you add something to the prompt, you pay a price - the prompt becomes harder, and the model's quality degrades. You can add this information with a flag, but still, there is a price - lots of flags complicate the usage.

Since I feel the use you describe is very specific, and won't apply to other people, I think it is more suitable for you to implement it, if needed, in your local hosting.

**Comment by TomDarmon** [comment]
I understand, thanks for the answer
