### ISSUE TITLE
bug in running pr agent Improve

### ISSUE THREAD

**Issue by zivkasp** [Codium-ai/pr-agent#777]
```
2024-03-12 09:47:50.886 | ERROR    | pr_agent.algo.utils:load_yaml:335 - Failed to parse AI prediction: while parsing a block mapping
  in "<unicode string>", line 2, column 1:
    code_suggestions:
    ^
expected <block end>, but found '<scalar>'
  in "<unicode string>", line 109, column 18:
    lang: {self.lang}"""
                     ^
2024-03-12 09:47:50.887 | INFO     | pr_agent.algo.utils:try_fix_yaml:357 - Failed to parse AI prediction after adding |-
```

no yaml in the pr, any idea?

**Comment by mrT23** [comment]
AI may fail to produce valid YAML. It happens.

is it reproducible? Does it happen every time?

If it happens consistently, share dramatically more details. Best option is a reproducible example for a public repo

**Comment by zivkasp** [comment]
It's reproducible on a specific PR, don't know what part of the code made it happen, if I don't want to share the code, can I run in debug mode or something to extra more detailed logs?

**Comment by mrT23** [comment]
- I won't play the guessing game.

- I need to understand which model you used, which configuration, whether was there something "special" about the PR (is it very large, for example), and many other factors.

- If you are a PR-Agent-pro user, just send the PR address, and we will look at the logs (they are deleted after 48 hours).

- If not, and you think this is a main problem for you, try to reproduce it on a public code, and share it

- From the little information you provide, I definitely don't think its a "bug". more like a limitation of the LLM, probably due to some edge condition you introduced in the PR.

**Comment by zivkasp** [comment]
Alright i'm not a premium user, i just want to open this to improve the product, i can't share the code. thanks anyway
