### ISSUE TITLE
Issues in Bitbucket pipeline

### ISSUE THREAD

**Issue by meanderix** [Codium-ai/pr-agent#789]
I've set up `bitbucket-pipelines.yml` to run the PR-agent on Bitbucket cloud. It works quite well, and I managed to connect it to our Azure OpenAI account by adding `OPENAI.API_TYPE=azure`, `OPENAI.DEPLOYMENT_ID=[deployment_id]`, `OPENAI.API_BASE=[azure endpoint]` as well as `OPENAI.API_VERSION=[api_version]`.

A few questions/comments:
1. I suppose we're running `docker run` within a container due to the fact that Bitbucket does not support environment variables with a dot?
2. The review command works, but it also produces an error:
```
2024-03-14 21:05:20.168 | ERROR    | pr_agent.tools.pr_reviewer:set_review_labels:387 - Failed to set review labels, error: 'NoneType' object is not iterable
```
3. The improve command works mostly, but sometimes produces warnings/errors:
```
2024-03-14 21:05:28.022 | WARNING  | pr_agent.algo.pr_processing:get_pr_multi_diffs:362 - Patch too large, skipping: [git-pkgs.sh](https://bitbucket.org/[redacted])
2024-03-14 21:05:28.022 | ERROR    | pr_agent.tools.pr_code_suggestions:_prepare_prediction_extended:303 - Error getting PR diff
2024-03-14 21:05:28.022 | ERROR    | pr_agent.tools.pr_code_suggestions:run:91 - No code suggestions found for PR.
```

**Comment by mrT23** [comment]
Take into account that BitBucket is an extremely outdated platform. 
It does not support almost anything, including trivial things like PR labels or collapsible (GitHub,GitLab, Azure and other do support it)
So that's the reason for (2). We might improve the error handling logging, but in practice, the results will be the same - no labels will appear.

Regarding (3), probably when you have changes in a single file that are too large (more than 8000 tokens), and we cannot give them to the model. So that's the reason for (3).

Regarding (1), I don't know if BitBucket supports it or not. You can try

**Comment by mrT23** [comment]
btw, the issue in (2) was fixed, you won't see that error message again. thanks for reporting

**Comment by meanderix** [comment]
> Take into account that BitBucket is an extremely outdated platform. It does not support almost anything, including trivial things like PR labels or collapsible (GitHub,GitLab, Azure and other do support it) So that's the reason for (2). We might improve the error handling logging, but in practice, the results will be the same - no labels will appear.

Thanks. We're already in a process of evaluating alternatives, so that might be the nail in the coffin. 🙂
